ignored = [
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

# client-go 10.0.0 uses apimachinery 2b1284ed4c93a43499e781493253e2ac5959c4fd
# and api a61488babbd64b32da2ed985e2e70fe7b4ffc05a (see Godep.json). go dep
# is unable to match Godep.json automatically so have to specify here.
[[constraint]]
    name = "k8s.io/client-go"
    version = "v10.0.0"
[[override]]
    name = "k8s.io/apimachinery"
    revision = "2b1284ed4c93a43499e781493253e2ac5959c4fd"
[[override]]
    name = "k8s.io/api"
    revision = "a61488babbd64b32da2ed985e2e70fe7b4ffc05a"

# Pin these dependencies to the exact versions listed in the
# Makefile. We can't even allow the patch version to float as that
# then causes compilation errors.
[[override]]
    name = "github.com/mholt/caddy"
    version = "=v0.11.1"

[[override]]
    name = "github.com/miekg/dns"
    version = "=v1.1.3"

[[override]]
    name = "github.com/prometheus/client_golang"
    version = "=v0.9.1"

[[override]]
    name = "github.com/openshift/cluster-api"
    branch = "release-4.0"
